# Generated by Django 4.2.2 on 2023-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='None', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
